import { Text } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/cesarzxk"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Text>Powered by </Text>
          <span className={styles.logo}>
            <Image src="/cesarzxk.svg" alt="cesarzxk" width={110} height={36} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
