import { Center, Grid, Spinner, VStack } from "@chakra-ui/react";
import dynamic from "next/dynamic";
import Head from "next/head";

import Footer from "../containers/Footer";
import Header from "../containers/Header";

const Map = dynamic(() => import("../components/Map"), {
  loading: () => (
    <Center h="86vh" w="100vw">
      <Spinner size="xl" color="#FC1616" />
    </Center>
  ),
  ssr: false,
});

export default function Home() {
  return (
    <VStack w="100vw" h="100vh" bgColor="#aaa">
      <Head>
        <title>imap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <Map />
      <Footer />
    </VStack>
  );
}
